// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-7YUhEYVDPudajtwAV0oHBJ9Gm8Wuheo',
    appId: '1:63958433851:web:e0ebda1cad37bf29ac9c1e',
    messagingSenderId: '63958433851',
    projectId: 'scrum-poker-38532',
    authDomain: 'scrum-poker-38532.firebaseapp.com',
    storageBucket: 'scrum-poker-38532.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDamaLc_XnRwd3YvbPDP3dD3bsDMOfbEcw',
    appId: '1:63958433851:android:fbffdd4e2c07730cac9c1e',
    messagingSenderId: '63958433851',
    projectId: 'scrum-poker-38532',
    storageBucket: 'scrum-poker-38532.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnkBgDFg_UIUzwGDTgBX8qdwxToJXKiiE',
    appId: '1:63958433851:ios:9bf305ad19453a15ac9c1e',
    messagingSenderId: '63958433851',
    projectId: 'scrum-poker-38532',
    storageBucket: 'scrum-poker-38532.firebasestorage.app',
    iosBundleId: 'com.example.scumPoker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnkBgDFg_UIUzwGDTgBX8qdwxToJXKiiE',
    appId: '1:63958433851:ios:9bf305ad19453a15ac9c1e',
    messagingSenderId: '63958433851',
    projectId: 'scrum-poker-38532',
    storageBucket: 'scrum-poker-38532.firebasestorage.app',
    iosBundleId: 'com.example.scumPoker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-7YUhEYVDPudajtwAV0oHBJ9Gm8Wuheo',
    appId: '1:63958433851:web:26efd361f1ea4145ac9c1e',
    messagingSenderId: '63958433851',
    projectId: 'scrum-poker-38532',
    authDomain: 'scrum-poker-38532.firebaseapp.com',
    storageBucket: 'scrum-poker-38532.firebasestorage.app',
  );
}
